This change updates the core_init_atmosphere cmake file to add new files added in commit c567151e6  (PR #1276). That PR updated the makefiles, but not the cmake files. That resulted in compile errors when building with cmake: src/core_init_atmosphere/mpas_init_atm_cases.F:48:11:
   48 |       use mpas_init_atm_gwd_gsl, only : calc_gsl_oro_data
      |           1
Fatal Error: Cannot open module file 'mpas_init_atm_gwd_gsl.mod' for reading at
(1): No such file or directory