Fix nonstandard declarations in module_ra_cam_support.F
Although the module_ra_cam_support module does provide an 'r8' parameter for
use in declaring double-precision real variables, r8 was defined as 8, which
leads to errors when building with the NAG compiler:

   Error: module_ra_cam_support.F, line 10: KIND value (8) does not specify a valid representation method
   Error: module_ra_cam_support.F, line 46: KIND value (8) does not specify a valid representation method
   Error: module_ra_cam_support.F, line 47: KIND value (8) does not specify a valid representation method
   Error: module_ra_cam_support.F, line 48: KIND value (8) does not specify a valid representation method
   ...

Defining r8 as R8KIND when compiling MPAS-Atmosphere resolves this issue.