Fix non-standard declarations of 8-byte integers in ESMF_BaseMod.F90
The ESMF_BaseMod module contains several non-standard declarations of 8-byte
integer variables. These were identified using the GNU compiler:

   ESMF_BaseMod.F90:75:20:

      75 |           integer*8 :: ptr
         |                    1
   Error: GNU Extension: Nonstandard type declaration INTEGER*8 at (1)

and also using the NAG compiler:

   Error: ESMF_BaseMod.F90, line 75: KIND value (8) does not specify a valid representation method
   Error: ESMF_BaseMod.F90, line 163: KIND value (8) does not specify a valid representation method

Since the ESMF_BaseMod module already defines a parameter for selecting 8-byte
integers, namely, ESMF_KIND_I8, all that is needed is to move the definition of
this (and related) parameters to appear earlier in the module and to then use

   integer(kind=ESMF_KIND_I8)

rather than

   integer(kind=8)

.