Correct Fortran 2008 compliance in module_libmassv.F
This commit corrects several issues with non-standard kind specifications in
module_libmassv.F. These issues were caught by the GNU Fortran compiler with
-std=f2008. For example:

  module_libmassv.F:25:8:

     25 |  real*8,dimension(*),intent(in):: x
        |        1
  Error: GNU Extension: Nonstandard type declaration REAL*8 at (1)

To provide standard kind specifications, local module variables R4KIND and
R8KIND, that should specify single- and double-precision, respectively, have
been defined as private parameters in module_libmassv.