This change updates the cmake files to incorporate NOAA's Unified Forecast System Unified Gravity Wave Physics suite of physics parameterizations.
git commit c567151e6  (PR #1276) introduced a new external dependency for
the physics code.  While the Makefiles were updated accordingly, the cmake
files were not.  This resulted in compile failures when building with cmake:
MPAS-Model-develop/src/core_atmosphere/physics/mpas_atmphys_finalize.F:14:6:
14 |  use cires_ugwpv1_module
|      1
Fatal Error: Cannot open module file 'cires_ugwpv1_module.mod' for reading at
(1): No such file or directory