This change adds mpas_atmphys_sfc_diagnostics.F to the atmosphere cmake file.
git commit 6ae4ac13e (PR 1242) added this file.
The file was added to the Makefile, but it wasn't added to the cmake file.
That resulted in a compile error when building with cmake:
MPAS/src/core_atmosphere/physics/mpas_atmphys_driver.F:26:6:

   26 |  use mpas_atmphys_sfc_diagnostics,only: atmphys_sfc_diagnostics
      |      1
Fatal Error: Cannot open module file 'mpas_atmphys_sfc_diagnostics.mod' for
reading at (1): No such file or directory
compilation terminated.